{% set version = "4.2.9" %}

package:
  name: jasper
  version: {{ version }}

source:
  url: https://github.com/jasper-software/jasper/releases/download/version-{{ version }}/jasper-{{ version }}.tar.gz
  sha256: f71cf643937a5fcaedcfeb30a22ba406912948ad4413148214df280afc425454

build:
  number: 1
  run_exports:
    # no info.  Leaving at default behavior.
    - {{ pin_subpackage('jasper') }}
  missing_dso_whitelist:   # [osx]
    - /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - ninja                             # [win]
  host:
    - libjpeg-turbo
    - libglu                            # [linux]
    - freeglut                          # [linux or win]
    - libgl-devel                       # [linux]
    - expat                             # [linux]
  run:
    - libjpeg-turbo
    - {{ pin_compatible('libglu') }}    # [linux]
    - {{ pin_compatible('freeglut') }}  # [linux or win]

test:
  commands:
    - if not exist %LIBRARY_BIN%\\jasper.dll exit 1  # [win]
    - jasper --version

about:
  home: http://www.ece.uvic.ca/~frodo/jasper/
  license: JasPer-2.0
  license_file: LICENSE.txt
  summary: A reference implementation of the codec specified in the JPEG-2000 Part-1 standard.

extra:
  recipe-maintainers:
    - akrherz
    - jakirkham
    - jhamman
    - ocefpaf
    - seanyen
