{% set version = "2.0.14" %}

package:
  name: jasper
  version: {{ version }}

source:
  url: http://www.ece.uvic.ca/~frodo/jasper/software/jasper-{{ version }}.tar.gz
  sha256: 2a1f61e55afe8b4ce8115e1508c5d7cb314d56dfcc2dd323f90c072f88ccf57b
  patches:
    - CVE-2018-9055-330751ce.patch

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # no info. Leaving at default behavior.
    - {{ pin_subpackage('jasper') }}
  missing_dso_whitelist:                                         # [osx]
    - /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}     # [not aarch64]
    - {{ cdt('mesa-dri-drivers') }}     # [not aarch64]
    - {{ cdt('libxdamage') }}           # [not aarch64]
    - {{ cdt('libselinux') }}           # [not aarch64]
    - {{ cdt('libxext') }}              # [not aarch64]
    - {{ cdt('libxfixes') }}            # [not aarch64]
    - {{ cdt('libxcb') }}               # [not aarch64]
    - {{ cdt('libxau') }}               # [not aarch64]
    - {{ cdt('libxi') }}                # [not aarch64]
    - {{ cdt('libxxf86vm') }}           # [not aarch64]
    - cmake
    - make
  host:
    - jpeg
    - libglu                            # [linux64]
    - freeglut                          # [linux64]
  run:
    - jpeg
    - {{ pin_compatible('libglu') }}    # [linux64]
    - {{ pin_compatible('freeglut') }}  # [linux64]

test:
  commands:
    - jasper --version

about:
  home: http://www.ece.uvic.ca/~frodo/jasper/
  license: JasPer 2.0
  license_file: LICENSE
  summary: 'A reference implementation of the codec specified in the JPEG-2000 Part-1 standard.'

extra:
  recipe-maintainers:
    - jakirkham
    - jhamman
    - ocefpaf
