{% set version = "1.900.1" %}
{% set jpeg_version = os.environ.get('JPEG_VERSION', '9b')|string %}
{% set build_number = "4" %}

package:
    name: jasper
    version: {{ version }}

source:
    fn: jasper-{{ version }}.zip
    url: http://www.ece.uvic.ca/~frodo/jasper/software/jasper-{{ version }}.zip
    sha1: 9c5735f773922e580bf98c7c7dfda9bbed4c5191

build:
    number: {{ build_number }}
    string: jpeg{{ jpeg_version }}_{{ build_number }}
    skip: True  # [win]

requirements:
    build:
        - jpeg {{ jpeg_version }}
    run:
        - jpeg {{ jpeg_version }}

test:
    commands:
        - jasper --version
        - conda inspect linkages -n _test jasper  # [linux]

about:
  home: http://www.ece.uvic.ca/~frodo/jasper/
  license: http://www.ece.uvic.ca/~frodo/jasper/LICENSE
  summary: A reference implementation of the codec specified in the JPEG-2000 Part-1 standard.

extra:
    recipe-maintainers:
        - jakirkham
        - jhamman
        - ocefpaf
        - 183amir
